package com.example.dashboard_backend.ingestion.dto;

import com.fasterxml.jackson.databind.JsonNode;

public record IngestRequest(
        String uploadToken,
        String userId, //auto generated
        String tableName, // autogenerated 
        String originalFilename, //for inline data sending
        JsonNode data
) {
}
