spring.application.name=dashboard-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/dashboard-db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

server.port=8080